CREATE TABLE IF NOT EXISTS `TRANSACTIONS`
(
	FLOW_ID VARCHAR(255),
	EXEC INT UNSIGNED,
	PROVIDER VARCHAR(50),
	TR_DATE DATE,
    TR_YEAR YEAR,
	TR_WEEK TINYINT(53) UNSIGNED,
	TR_MONTH TINYINT(12) UNSIGNED,
	TR_DAY TINYINT(31) UNSIGNED,
	TR_WEEKDAY TINYINT(7) UNSIGNED,
	TR_HOUR TINYINT(24) UNSIGNED,
	TR_TYPE VARCHAR(10),
	TR_LOCATION VARCHAR(50),
	TR_BENEFICIARY VARCHAR(300),
	TR_METHOD VARCHAR(30),
	#TR_INFO VARCHAR(1000),
	TR_VALUE DECIMAL(8,2),
	TR_UOM CHAR(3)
);