CREATE OR REPLACE VIEW `CALENDAR` AS
(
	SELECT 
		c.DT, 
        EXTRACT(YEAR_MONTH FROM c.DT) YEARMONTH,
		EXTRACT(YEAR FROM c.DT) D_YEAR,
        EXTRACT(MONTH FROM c.DT) D_MONTH,
        EXTRACT(WEEK FROM c.DT) D_WEEK,
        EXTRACT(QUARTER FROM c.DT) D_QUARTER,
        CONCAT(EXTRACT(YEAR FROM c.DT), EXTRACT(QUARTER FROM c.DT)) D_YEARQUARTER,
        DAYOFYEAR(c.DT) DAY_OF_YEAR,
        DAYOFWEEK(c.DT) DAY_OF_WEEK,
        DAYNAME(c.DT) DAY_NAME
	FROM
	(
		SELECT
			DATE_ADD((SELECT MIN(TR_DATE) FROM TRANSACTIONS), INTERVAL D DAY) DT
		FROM
		(
			SELECT 
				a.N+(b.N * 10)+(c.N * 100)+(d.N *1000) D
			FROM
				(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
				,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
				,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
				,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) d
		) t   
		WHERE
			t.D <= DATEDIFF(CURRENT_DATE(), (SELECT MIN(TR_DATE) FROM TRANSACTIONS))
	) c
    ORDER BY DT DESC
);