CREATE OR REPLACE VIEW `V_REVENUES` AS
(
	SELECT
		TR_YEAR,
		TR_MONTH,
		TR_YEARMONTH,
		TR_QUARTER,
		REV_M/DAYS_M REV_1M,
		(
			LEAD(REV_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC) 
			+ LEAD(REV_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		)
		/
		(
			LEAD(DAYS_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		) 
		REV_3M,
		(
			LEAD(REV_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC) 
			+ LEAD(REV_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		)
		/
		(
			LEAD(DAYS_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		) 
		REV_6M,
		(
			LEAD(REV_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC) 
			+ LEAD(REV_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,7,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,8,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,9,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		)
		/
		(
			LEAD(DAYS_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,7,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,8,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,9,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		) 
		REV_9M,
			(
			LEAD(REV_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC) 
			+ LEAD(REV_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,7,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,8,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,9,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,10,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,11,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(REV_M,12,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		)
		/
		(
			LEAD(DAYS_M,1,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,2,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,3,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,4,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,5,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,6,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,7,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,8,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,9,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,10,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,11,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
			+ LEAD(DAYS_M,12,0) OVER (PARTITION BY TRUE ORDER BY TR_YEAR DESC, TR_MONTH DESC)
		) 
		REV_12M,
		SUM(REV_M) OVER (PARTITION BY TR_YEAR,TR_QUARTER ORDER BY TR_MONTH) REV_QUARTER
	FROM
	(
		SELECT 
			TR_YEAR,
			TR_MONTH,
			EXTRACT(YEAR_MONTH FROM TR_DATE) TR_YEARMONTH,
			EXTRACT(QUARTER FROM TR_DATE) TR_QUARTER,
			SUM(TR_VALUE) REV_M,
			DATEDIFF(LEAST(CURRENT_DATE(),DATE(LAST_DAY(CONCAT(TR_YEAR,'-',TR_MONTH,'-01')))),CONCAT(TR_YEAR,'-',TR_MONTH,'-01'))+1 DAYS_M
		FROM TRANSACTIONS
        WHERE TR_TYPE = "revenue"
		GROUP BY TR_YEAR, TR_MONTH
	) t
	-- ORDER BY TR_YEAR DESC, TR_MONTH DESC
);