CREATE OR REPLACE VIEW `OUTSTANDING_FEES` AS
(
	SELECT
		DT,
		SUM(DATEDIFF(f.FEE_DUE_DATE, DT)*f.FEE_AMOUNT) FEES_OUTSTANDING
	FROM CALENDAR t
	LEFT JOIN SPENDING_FEES f
	ON t.DT BETWEEN f.FEE_START_DATE AND f.FEE_DUE_DATE
	GROUP BY DT
);