CREATE OR REPLACE VIEW `DAILY_COST_TRENDS` AS
(
	SELECT
		*, 
		(2W_AVG+1M_AVG+1Q_AVG)/3 AS DAILY_AVG
	FROM
	(
		select 
			DT, 
			DAILY_COST, 
			AVG(DAILY_COST) OVER (ORDER BY DT ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS 2W_AVG,
			AVG(DAILY_COST) OVER (ORDER BY DT ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS 1M_AVG,
			AVG(DAILY_COST) OVER (ORDER BY DT ROWS BETWEEN 89 PRECEDING AND CURRENT ROW) AS 1Q_AVG
		from INCOME_STATEMENT_DAILY
	) S
	ORDER BY DT DESC
);
