CREATE OR REPLACE VIEW `V_FEES_OUTSTANDING_EOM` AS
(
	SELECT
		DT,
		AVG(OUTSTANDING_FEE) OUTSTANDING_FEE # in case last date is inserted 2 times
	FROM INCOME_STATEMENT_DAILY
	WHERE DT = LAST_DAY(DT) OR DT=(SELECT MAX(DT) FROM CALENDAR)
	GROUP BY DT
	-- ORDER BY DT DESC
);