CREATE OR REPLACE VIEW `INCOME_STATEMENT_MONTHLY` AS
(
	SELECT
		TR_YEAR,
		TR_MONTH,
		REVENUES,
		EXPENSES,
		AMORTIZED_COST,
		FEES,
		EARNINGS,
		MARGIN,
		t.OUTSTANDING_FEE
	FROM
	(
		SELECT
			EXTRACT(YEAR FROM DT) TR_YEAR,
			EXTRACT(MONTH FROM DT) TR_MONTH,
			EXTRACT(YEAR_MONTH FROM DT) TR_YEAR_MONTH,
			SUM(REVENUES) REVENUES,
			SUM(EXPENSES) EXPENSES,
			SUM(AMORTIZED_COST) AMORTIZED_COST,
			SUM(APPLICABLE_FEE) FEES,
			SUM(EARNINGS) EARNINGS,
			SUM(EARNINGS)/SUM(REVENUES) MARGIN
		FROM INCOME_STATEMENT_DAILY
		GROUP BY EXTRACT(YEAR_MONTH FROM DT)
	) s
	LEFT JOIN V_FEES_OUTSTANDING_EOM t
	ON s.TR_YEAR_MONTH=EXTRACT(YEAR_MONTH FROM t.DT)

	ORDER BY 1 DESC,2 DESC
);