CREATE OR REPLACE VIEW `INCOME_STATEMENT_YEARLY` AS
(
	SELECT
		EXTRACT(YEAR FROM DT) TR_YEAR,
		SUM(REVENUES) REVENUES,
		SUM(EXPENSES) EXPENSES,
		SUM(AMORTIZED_COST) AMORTIZED_COST,
		SUM(APPLICABLE_FEE) FEES,
		SUM(EARNINGS) EARNINGS,
		SUM(EARNINGS)/SUM(REVENUES) MARGIN
	FROM INCOME_STATEMENT_DAILY
	GROUP BY
		EXTRACT(YEAR FROM DT)
	ORDER BY 1 DESC
);